/* Axes: a domain, a pixel range, and the tick marks between them.
 *
 * This is the part of a plotting library that everything else leans on, so it
 * is kept free of React and of any notion of what is being drawn. Give it the
 * numbers a series will show and the two pixel coordinates the axis runs
 * between, and it answers three questions: where does a value land, what value
 * is at this pixel, and where do the labelled ticks go.
 *
 * ⚠️ The pixel range is passed in the direction the caller wants. A y axis is
 * built with (bottom, top) because SVG's y grows downward; `reverse` is then
 * an *authoring* choice on top of that — the one an H–R diagram needs, where
 * temperature increases to the left. Folding the two together produced an axis
 * that flipped when you switched the tool to paper mode. */

export type ScaleKind = 'linear' | 'log' | 'category'

export type TickFormat = 'auto' | 'int' | 'sci' | 'percent' | 'si' | 'comma'

export interface AxisSpec {
  label?: string
  scale?: ScaleKind
  /** null / undefined = fit the data */
  min?: number | null
  max?: number | null
  /** run the axis the other way — H–R diagrams, depth profiles */
  reverse?: boolean
  /** keep 0 inside an auto range, so bar heights stay honest */
  zero?: boolean
  /** how many labelled ticks to aim for */
  tickCount?: number
  /** force the spacing instead of choosing a nice one */
  tickStep?: number | null
  format?: TickFormat
  decimals?: number | null
  prefix?: string
  suffix?: string
  /** degrees to rotate tick labels — long category names */
  angle?: number
  grid?: boolean
  minorGrid?: boolean
  /** draw the spine */
  line?: boolean
  /** headroom added at both ends of an auto range, as a fraction of the span */
  pad?: number
}

export interface TickMark {
  /** in data units — a category axis uses the category's index */
  v: number
  label: string
  /** superscript tail, so 10⁻⁴ is one text element and not a picture of one */
  sup?: string
}

export interface Axis {
  kind: ScaleKind
  /** domain, in data units */
  min: number
  max: number
  categories: string[]
  ticks: TickMark[]
  /** unlabelled positions, in data units */
  minor: number[]
  /** data value → pixel */
  px: (v: number) => number
  /** pixel → data value */
  inv: (p: number) => number
  /** pixel width of one category slot; the full range when not categorical */
  band: number
  /** the two ends, in pixels, after `reverse` */
  p0: number
  p1: number
  spec: AxisSpec
  /** the tick step actually used — label formatting needs it */
  step: number
}

/* ---------- nice numbers ---------- */

/** The Heckbert rule: round to 1, 2, 5 or 10 times a power of ten. Every
 *  plotting library uses some version of it because those are the intervals a
 *  reader can subdivide in their head. */
export function niceNum(x: number, round: boolean): number {
  if (!(x > 0)) return 1
  const exp = Math.floor(Math.log10(x))
  const f = x / Math.pow(10, exp)
  const nf = round
    ? f < 1.5
      ? 1
      : f < 3
        ? 2
        : f < 7
          ? 5
          : 10
    : f <= 1
      ? 1
      : f <= 2
        ? 2
        : f <= 5
          ? 5
          : 10
  return nf * Math.pow(10, exp)
}

/** Round `n` to 12 significant digits.
 *
 *  Accumulating a tick position by repeated addition lands on 0.30000000000000004,
 *  and a tick labelled that way is the single most common bug in hand-rolled
 *  chart code. Ticks are generated by multiplication from an index here, and
 *  this cleans up what multiplication still leaves. */
const clean = (n: number) => (n === 0 ? 0 : +n.toPrecision(12))

/* ---------- domain ---------- */

const finite = (vs: number[]) => vs.filter((v) => Number.isFinite(v))

function autoDomain(values: number[], spec: AxisSpec): [number, number] {
  const vs = finite(values)
  if (!vs.length) return [0, 1]
  let lo = Math.min(...vs)
  let hi = Math.max(...vs)
  if (spec.zero) {
    lo = Math.min(lo, 0)
    hi = Math.max(hi, 0)
  }
  if (lo === hi) {
    // a flat series still needs an axis to sit on
    const d = Math.abs(lo) > 1e-12 ? Math.abs(lo) * 0.1 : 1
    lo -= d
    hi += d
  }
  const pad = spec.pad ?? 0
  if (pad > 0) {
    const span = hi - lo
    // padding must not invent a negative range under a bar chart
    const loPad = spec.zero && lo === 0 ? 0 : span * pad
    lo -= loPad
    hi += span * pad
  }
  return [lo, hi]
}

/* ---------- linear ticks ---------- */

function linearTicks(
  min: number,
  max: number,
  spec: AxisSpec,
  snap: boolean,
): { ticks: number[]; minor: number[]; step: number; domain: [number, number] } {
  const target = Math.max(2, spec.tickCount ?? 6)
  const span = max - min || 1
  const step = spec.tickStep && spec.tickStep > 0 ? spec.tickStep : niceNum(span / (target - 1), true)

  /* Only an axis anchored at zero grows out to a whole tick.
   *
   * That axis is read as a scale — "the tallest bar is 45 out of 50" — and a
   * round top is part of what it says. An axis that merely frames a cloud of
   * points is read as a window, and rounding it out wastes the plot: data
   * spanning −6…6 snaps to −10…10 and then fills a third of the panel. */
  const lo = snap ? Math.floor(min / step) * step : min
  const hi = snap ? Math.ceil(max / step) * step : max

  const ticks: number[] = []
  const start = Math.ceil(lo / step - 1e-9)
  const end = Math.floor(hi / step + 1e-9)
  // a pathological explicit step must not hang the render
  if (end - start > 5000) return { ticks: [lo, hi], minor: [], step, domain: [lo, hi] }
  for (let i = start; i <= end; i++) ticks.push(clean(i * step))

  const sub = step / 10 > 0 && niceNum(step / 5, true) === step / 5 ? 5 : 2
  const minor: number[] = []
  const mstep = step / sub
  for (let i = Math.ceil(lo / mstep - 1e-9); i <= Math.floor(hi / mstep + 1e-9); i++) {
    const v = clean(i * mstep)
    if (!ticks.some((t) => Math.abs(t - v) < mstep * 1e-6)) minor.push(v)
  }
  return { ticks, minor, step, domain: [lo, hi] }
}

/* ---------- log ticks ---------- */

const POSITIVE_FLOOR = 1e-300

function logTicks(
  min: number,
  max: number,
  fixedEnds: boolean,
): { ticks: number[]; minor: number[]; domain: [number, number] } {
  const lo = Math.max(min, POSITIVE_FLOOR)
  const hi = Math.max(max, lo * 10)
  const e0 = fixedEnds ? Math.log10(lo) : Math.floor(Math.log10(lo))
  const e1 = fixedEnds ? Math.log10(hi) : Math.ceil(Math.log10(hi))
  const decades = e1 - e0

  const ticks: number[] = []
  const minor: number[] = []
  // over many decades, label every 10th/100th power instead of crowding
  const everyN = decades > 24 ? 5 : decades > 12 ? 2 : 1
  for (let e = Math.ceil(e0); e <= Math.floor(e1); e++) {
    if (e % everyN === 0) ticks.push(Math.pow(10, e))
  }
  if (decades <= 2) {
    // inside two decades the 2·10ⁿ and 5·10ⁿ rungs are worth labelling
    for (let e = Math.floor(e0); e <= Math.ceil(e1); e++)
      for (const m of [2, 5]) {
        const v = m * Math.pow(10, e)
        if (v >= Math.pow(10, e0) - 1e-12 && v <= Math.pow(10, e1) + 1e-12) ticks.push(v)
      }
    ticks.sort((a, b) => a - b)
  }
  for (let e = Math.floor(e0); e <= Math.ceil(e1); e++)
    for (let m = 2; m <= 9; m++) {
      const v = m * Math.pow(10, e)
      if (v < Math.pow(10, e0) || v > Math.pow(10, e1)) continue
      if (!ticks.some((t) => Math.abs(t / v - 1) < 1e-9)) minor.push(v)
    }
  return { ticks, minor, domain: [Math.pow(10, e0), Math.pow(10, e1)] }
}

/* ---------- formatting ---------- */

const SI = [
  { e: 12, s: 'T' },
  { e: 9, s: 'G' },
  { e: 6, s: 'M' },
  { e: 3, s: 'k' },
  { e: 0, s: '' },
  { e: -3, s: 'm' },
  { e: -6, s: 'µ' },
  { e: -9, s: 'n' },
]

const groupThousands = (s: string) => {
  const [i, f] = s.split('.')
  return i.replace(/\B(?=(\d{3})+(?!\d))/g, ',') + (f ? `.${f}` : '')
}

/** Decimals that keep two consecutive ticks distinct without adding noise. */
function autoDecimals(step: number): number {
  if (!(step > 0)) return 0
  const d = Math.ceil(-Math.log10(step) + 1e-9)
  return Math.min(10, Math.max(0, d))
}

export function formatTick(v: number, spec: AxisSpec, step: number): TickMark {
  const fmt = spec.format ?? 'auto'
  const dec = spec.decimals
  const wrap = (label: string, sup?: string): TickMark => ({
    v,
    label: `${spec.prefix ?? ''}${label}${sup ? '' : (spec.suffix ?? '')}`,
    sup,
  })

  if (fmt === 'percent') return wrap(`${+(v * 100).toFixed(dec ?? autoDecimals(step * 100))}%`)
  if (fmt === 'int') return wrap(groupThousands(String(Math.round(v))))
  if (fmt === 'sci') return sciTick(v, spec, dec ?? 1)
  if (fmt === 'si') {
    if (v === 0) return wrap('0')
    const unit = SI.find((u) => Math.abs(v) >= Math.pow(10, u.e)) ?? SI[SI.length - 1]
    const scaled = v / Math.pow(10, unit.e)
    return wrap(`${+scaled.toFixed(dec ?? (Math.abs(scaled) < 10 ? 1 : 0))}${unit.s}`)
  }
  if (fmt === 'comma') return wrap(groupThousands((dec === null || dec === undefined ? v : +v.toFixed(dec)).toString()))

  // auto: plain decimals in the range a reader can hold, exponent outside it
  if (v === 0) return wrap('0')
  const mag = Math.abs(v)
  if (mag >= 1e5 || mag < 1e-4) return sciTick(v, spec, dec ?? 0)
  const d = dec ?? autoDecimals(step)
  return wrap(String(+v.toFixed(d)))
}

function sciTick(v: number, spec: AxisSpec, decimals: number): TickMark {
  if (v === 0) return { v, label: `${spec.prefix ?? ''}0${spec.suffix ?? ''}` }
  const exp = Math.floor(Math.log10(Math.abs(v)))
  const man = v / Math.pow(10, exp)
  const sup = String(exp).replace(/-/g, '−')
  // a pure power of ten reads as 10ⁿ, not 1×10ⁿ
  const head = Math.abs(man - 1) < 1e-9 ? '10' : `${+man.toFixed(decimals)}×10`
  return { v, label: `${spec.prefix ?? ''}${head}`, sup }
}

/** The same rules, for a data label rather than a tick. */
export const formatValue = (v: number, spec: AxisSpec = {}, step = 0): string => {
  const t = formatTick(v, spec, step || Math.max(1e-12, Math.abs(v) / 100))
  return t.sup ? `${t.label}^${t.sup}` : t.label
}

/* ---------- building ---------- */

export interface AxisInput {
  /** every value a series will place on this axis */
  values?: number[]
  /** category names, in order — makes the axis categorical */
  categories?: string[]
}

export function buildAxis(
  spec: AxisSpec,
  input: AxisInput,
  pa: number,
  pb: number,
): Axis {
  const kind: ScaleKind = input.categories?.length ? 'category' : (spec.scale ?? 'linear')
  const rev = !!spec.reverse
  const [p0, p1] = rev ? [pb, pa] : [pa, pb]

  if (kind === 'category') {
    const cats = input.categories ?? []
    const n = Math.max(1, cats.length)
    // half a slot of margin at each end, so the first bar is not on the spine
    const min = -0.5
    const max = n - 0.5
    const px = (v: number) => p0 + ((v - min) / (max - min)) * (p1 - p0)
    return {
      kind,
      min,
      max,
      categories: cats,
      ticks: cats.map((label, i) => ({ v: i, label })),
      minor: [],
      px,
      inv: (p) => min + ((p - p0) / (p1 - p0)) * (max - min),
      band: Math.abs(p1 - p0) / n,
      p0,
      p1,
      spec,
      step: 1,
    }
  }

  const values = input.values ?? []
  const pinned = spec.min !== null && spec.min !== undefined && spec.max !== null && spec.max !== undefined
  /* ⚠️ Linear padding is meaningless on a log axis and actively harmful: five
     percent of a span that runs from 1e-8 to 1e-4 is 5e-6, which drags the
     bottom of the axis below zero and there is no such place. A log axis gets
     its headroom from snapping out to whole decades instead. `zero` goes for
     the same reason — a log axis has no zero to include. */
  const auto = autoDomain(
    kind === 'log' ? values.filter((v) => v > 0) : values,
    kind === 'log' ? { ...spec, pad: 0, zero: false } : spec,
  )
  let lo = spec.min ?? auto[0]
  let hi = spec.max ?? auto[1]
  if (!(hi > lo)) hi = lo + (Math.abs(lo) || 1)

  // an axis the author pinned keeps its ends exactly; so does one that is
  // framing data rather than measuring from zero
  const snap = !pinned && !!spec.zero
  if (kind === 'log') {
    const t = logTicks(lo, hi, !snap)
    if (snap) [lo, hi] = t.domain
    const tl = Math.log10(lo)
    const th = Math.log10(hi)
    const px = (v: number) =>
      p0 + ((Math.log10(Math.max(v, POSITIVE_FLOOR)) - tl) / (th - tl || 1)) * (p1 - p0)
    const shown = t.ticks.filter((v) => v >= lo * (1 - 1e-9) && v <= hi * (1 + 1e-9))
    /* One axis, one notation. Deciding per tick gives an axis reading 0.001,
       10⁻⁴, 10⁻⁵ — three ways of writing the same kind of number stacked on
       top of each other. */
    const plainAll = shown.every((v) => plainDecade(v))
    return {
      kind,
      min: lo,
      max: hi,
      categories: [],
      ticks: shown.map((v) => logLabel(v, spec, plainAll)),
      minor: t.minor.filter((v) => v >= lo && v <= hi),
      px,
      inv: (p) => Math.pow(10, tl + ((p - p0) / (p1 - p0)) * (th - tl)),
      band: Math.abs(p1 - p0),
      p0,
      p1,
      spec,
      step: 1,
    }
  }

  const t = linearTicks(lo, hi, spec, snap)
  ;[lo, hi] = t.domain
  const px = (v: number) => p0 + ((v - lo) / (hi - lo || 1)) * (p1 - p0)
  return {
    kind: 'linear',
    min: lo,
    max: hi,
    categories: [],
    ticks: t.ticks.filter((v) => v >= lo - 1e-9 && v <= hi + 1e-9).map((v) => formatTick(v, spec, t.step)),
    minor: t.minor.filter((v) => v >= lo && v <= hi),
    px,
    inv: (p) => lo + ((p - p0) / (p1 - p0)) * (hi - lo),
    band: Math.abs(p1 - p0),
    p0,
    p1,
    spec,
    step: t.step,
  }
}

/** Is this a value a reader takes in without an exponent? */
function plainDecade(v: number): boolean {
  const e = Math.log10(v)
  if (Math.abs(e - Math.round(e)) > 1e-9) return true // 2·10ⁿ rungs read plainly
  const exp = Math.round(e)
  return exp >= -3 && exp <= 4
}

/** A log tick reads as a power of ten unless the whole axis fits in the range
 *  a reader takes in as plain decimals, or the author asked for a format. */
function logLabel(v: number, spec: AxisSpec, plainAll: boolean): TickMark {
  if (spec.format && spec.format !== 'auto') return formatTick(v, spec, v / 10)
  const e = Math.log10(v)
  const whole = Math.abs(e - Math.round(e)) < 1e-9
  if (plainAll || !whole)
    return { v, label: `${spec.prefix ?? ''}${+v.toPrecision(12)}${spec.suffix ?? ''}` }
  return { v, label: `${spec.prefix ?? ''}10`, sup: String(Math.round(e)).replace(/-/g, '−') }
}
